### PR TITLE
Hotfix/0.1.2

### PR DESCRIPTION
**Pull request by byb121**
* cleaned output header of `get_tmp_fpkm.py`; It now produces compressed output by default, and has a `--no-compression` option to disable it.

### CODE REVIEW

**Comment by byb121** [comment]
@keiranmraine  @sb43 if no objection, I'll merge.

**Review by sb43 — APPROVED** [review]
Would it be good to add citation for gtftools? at the end of README

**Comment by byb121** [comment]
@sb43 already in readme.md.

**Comment by sb43** [comment]
> @sb43 already in readme.md.
good
Sorry closed pull request inadvertently

**Review by keiranmraine — CHANGES_REQUESTED** [review]
The version numbers will become very confusing if they don't align with the release tag.  Discussed with @byb121 that a comment in the readme about what `gtftools` (just spotted typo in readme) was based on and align all version numbers.

**Comment by byb121** [comment]
@kr2 done, shall we merge?

**Comment by keiranmraine** [comment]
Via hubflow yes.

**Pull request closed without merging**
