### PR TITLE
Do NOT merge: REVIEW ONLY Release/0.1.0

### PR DESCRIPTION
**Pull request by byb121**

### CODE REVIEW

**Review by sb43 — COMMENTED** [review]
looks good to me

**Comment by byb121** [comment]
I need to test it under singularity.

**Comment by byb121** [comment]
Tested under Singularity, worked fine!

**Comment by keiranmraine** [comment]
@yx2 did you consider using a `--prefix` install with pip3 so that build stages could be used and drop `python3.7-dev`, `python3.7-distutils` to minimise the image size?  Not essential, but better practice.

**Comment by byb121** [comment]
@keiranmraine Using the current method to install pip3 requires `python3.7-distutils`. Got rid of `python3.7-dev` though, which saved about 100MB on image size. Thanks :)

**Pull request closed without merging**
